# Generated by Django 4.1.5 on 2023-01-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='degree',
            field=models.CharField(default='BTech', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='program',
            field=models.CharField(default='ICT', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.IntegerField(default='2025'),
        ),
    ]
