# Generated by Django 4.1.5 on 2023-01-12 10:12

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0003_alter_profile_degree_alter_profile_program_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('user', models.CharField(max_length=30)),
                ('id', models.UUIDField(default=uuid.UUID('ba8e7919-c04d-461d-a986-39d8f48aae47'), primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('posted_at', models.DateTimeField(default=datetime.datetime.now)),
                ('main_blog', models.TextField()),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
