# Generated by Django 4.1.5 on 2023-01-12 10:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0004_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b1647f5-7f39-458b-95e0-5f9d6f323d0e'), primary_key=True, serialize=False),
        ),
    ]
