# Generated by Django 4.1.5 on 2023-01-13 09:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0007_post_job_profile_post_offer_type_post_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dd10fb82-d0b8-4564-805f-ebf778486aaf'), primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='job_profile',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='offer_type',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.IntegerField(),
        ),
    ]
