# Generated by Django 4.1.5 on 2023-01-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0010_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='program',
            field=models.CharField(max_length=60),
        ),
    ]
