# Generated by Django 4.1.5 on 2023-01-21 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0011_alter_profile_program'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=60)),
                ('ctc', models.IntegerField(default=32)),
                ('resume', models.FileField(upload_to='resumes')),
                ('main_prof', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WOC.profile')),
            ],
        ),
    ]
