# Generated by Django 4.1.5 on 2023-01-21 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0014_alter_addprofile_ctc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprofile',
            name='resume',
            field=models.FileField(null=True, upload_to='resumes'),
        ),
    ]
