# Generated by Django 4.1.5 on 2023-01-21 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0015_alter_addprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprofile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes'),
        ),
    ]
