# Generated by Django 4.1.5 on 2023-01-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0016_alter_addprofile_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprofile',
            name='placed_at',
            field=models.CharField(default=None, max_length=60),
        ),
        migrations.AlterField(
            model_name='addprofile',
            name='position',
            field=models.CharField(default=None, max_length=60),
        ),
    ]
