# Generated by Django 4.1.5 on 2023-01-21 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0018_alter_addprofile_placed_at_alter_addprofile_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addprofile',
            name='placed_at',
            field=models.CharField(blank=True, default='DuMmY', max_length=60),
        ),
        migrations.AlterField(
            model_name='addprofile',
            name='position',
            field=models.CharField(blank=True, default='DuMmY', max_length=60),
        ),
    ]
