# Generated by Django 4.1.5 on 2023-01-21 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0020_remove_addprofile_main_prof_remove_addprofile_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addprofile',
            name='main_prof',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WOC.profile'),
        ),
        migrations.AlterField(
            model_name='addprofile',
            name='insta_prof',
            field=models.TextField(default='none'),
        ),
        migrations.AlterField(
            model_name='addprofile',
            name='linkedin_prof',
            field=models.TextField(default='none'),
        ),
    ]
