# Generated by Django 4.1.5 on 2023-01-21 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0022_addprofile_resume'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddProfile',
        ),
    ]
