# Generated by Django 4.1.5 on 2023-01-21 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0023_delete_addprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctc', models.IntegerField(default=-1)),
                ('placed_at', models.CharField(blank=True, default='DuMmY', max_length=60)),
                ('position', models.CharField(blank=True, default='DuMmY', max_length=60)),
                ('linkedin_prof', models.TextField(default='none')),
                ('insta_prof', models.TextField(default='none')),
                ('main_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='WOC.profile')),
            ],
        ),
    ]
