# Generated by Django 4.1.5 on 2023-01-22 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0026_post_liked_by_alter_post_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(default=None, to='WOC.profile'),
        ),
    ]
