# Generated by Django 4.1.5 on 2023-01-24 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WOC', '0032_post_liked_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(blank=True, default=None, to='WOC.profile'),
        ),
    ]
